#!/usr/bin/env python3
"""Generates the glyph-name and simple-font encoding tables in justpdf-core/src/font/.

Usage: gen-font-tables.py <glyphlist.txt> <encodings.js> <repo root>

- glyphlist.txt: the Adobe Glyph List, adobe-type-tools/agl-aglfn
- encodings.js:  pdf.js src/core/encodings.js (the ISO 32000-2 Annex D tables)

Writes font/agl.rs and font/encoding_tables.rs, and prints how the WinAnsi table
derived from encodings.js differs from the hand-written one in encoding.rs.
"""
import re
import sys

glyphlist_path, encodings_path, root = sys.argv[1:4]

# --- Adobe Glyph List ---
agl_lines = open(glyphlist_path, encoding="utf-8").read().splitlines()
header = []
for line in agl_lines:
    if not line.startswith("#"):
        break
    header.append(line[1:].rstrip())
agl = {}
for line in agl_lines:
    if line.startswith("#") or not line.strip():
        continue
    name, codes = line.split(";")
    agl[name] = "".join(chr(int(c, 16)) for c in codes.split())


def rust_str(s):
    return '"' + "".join(f"\\u{{{ord(c):04X}}}" for c in s) + '"'


with open(f"{root}/justpdf-core/src/font/agl.rs", "w", encoding="utf-8", newline="\n") as out:
    out.write("//! The Adobe Glyph List: glyph name to Unicode, sorted by name.\n")
    out.write("//! Generated by scripts/gen-font-tables.py from glyphlist.txt (adobe-type-tools/agl-aglfn).\n")
    out.write("//!\n")
    for line in header:
        out.write(f"//!{line}\n" if line else "//!\n")
    out.write("\n")
    out.write("pub(crate) static AGL: &[(&str, &str)] = &[\n")
    for name in sorted(agl, key=lambda n: n.encode()):
        out.write(f'    ("{name}", {rust_str(agl[name])}),\n')
    out.write("];\n")

# --- Annex D encodings ---
js = open(encodings_path, encoding="utf-8").read()


def table(name):
    body = re.search(rf"const {name} = \[(.*?)\];", js, re.S).group(1)
    names = re.findall(r'"([^"]*)"', body)
    assert len(names) == 256, (name, len(names))
    return names


def to_chars(names, label):
    chars = []
    for code, glyph in enumerate(names):
        if not glyph:
            chars.append(None)
            continue
        u = agl.get(glyph)
        assert u is not None and len(u) == 1, (label, code, glyph, u)
        chars.append(u)
    return chars


standard = to_chars(table("StandardEncoding"), "Standard")
mac_roman = to_chars(table("MacRomanEncoding"), "MacRoman")
win_ansi = to_chars(table("WinAnsiEncoding"), "WinAnsi")


def rust_table(chars):
    cells = [f"'\\u{{{ord(c):04X}}}'" if c else "'\\0'" for c in chars]
    rows = ["    " + ", ".join(cells[i : i + 8]) + "," for i in range(0, 256, 8)]
    return "[\n" + "\n".join(rows) + "\n]"


with open(f"{root}/justpdf-core/src/font/encoding_tables.rs", "w", encoding="utf-8", newline="\n") as out:
    out.write("//! StandardEncoding and MacRomanEncoding, code to Unicode; '\\0' marks a code with no glyph.\n")
    out.write("//! Generated by scripts/gen-font-tables.py from ISO 32000-2 Annex D, as transcribed in\n")
    out.write("//! pdf.js src/core/encodings.js, and the Adobe Glyph List.\n\n")
    out.write(f"pub(crate) static STANDARD_TO_UNICODE: [char; 256] = {rust_table(standard)};\n\n")
    out.write(f"pub(crate) static MAC_ROMAN_TO_UNICODE: [char; 256] = {rust_table(mac_roman)};\n\n")
    out.write("/// StandardEncoding, MacRomanEncoding and WinAnsiEncoding, code to glyph name; \"\" marks a code with no glyph.\n")
    for label, names in (
        ("STANDARD_GLYPH_NAMES", table("StandardEncoding")),
        ("MAC_ROMAN_GLYPH_NAMES", table("MacRomanEncoding")),
        ("WIN_ANSI_GLYPH_NAMES", table("WinAnsiEncoding")),
    ):
        cells = ", ".join(f'"{n}"' for n in names)
        out.write(f"pub(crate) static {label}: [&str; 256] = [{cells}];\n\n")

import subprocess

subprocess.run(
    ["rustfmt", "--edition", "2024",
     f"{root}/justpdf-core/src/font/agl.rs",
     f"{root}/justpdf-core/src/font/encoding_tables.rs"],
    check=True,
)

# --- cross-check the hand-written WinAnsi table ---
existing = {i: chr(i) for i in range(256)}
src = open(f"{root}/justpdf-core/src/font/encoding.rs", encoding="utf-8").read()
win_ansi_src = src[src.index("static WINANSI_TO_UNICODE") : src.index("static PDFDOC_TO_UNICODE")]
overrides = re.findall(r"table\[0x([0-9A-F]{2})\] = '\\u\{([0-9A-F]+)\}';", win_ansi_src)
assert overrides, "no overrides read from WINANSI_TO_UNICODE"
for code, cp in overrides:
    existing[int(code, 16)] = chr(int(cp, 16))
diffs = [
    (code, win_ansi[code], existing[code])
    for code in range(256)
    if win_ansi[code] is not None and win_ansi[code] != existing[code]
]
print(f"AGL entries: {len(agl)}")
print(f"WinAnsi codes defined in Annex D that differ from encoding.rs: {len(diffs)}")
for code, annex, ours in diffs:
    print(f"  0x{code:02X}: Annex D U+{ord(annex):04X}, encoding.rs U+{ord(ours):04X}")
undefined_but_mapped = [c for c in range(256) if win_ansi[c] is None and c >= 0x20]
print(f"WinAnsi codes >= 0x20 undefined in Annex D: {[hex(c) for c in undefined_but_mapped]}")
